Criando Arrays - matrizes

In [16]:
import numpy

arrl = numpy.array([10,21,32,43,48,1,2,64,11,90])


print(arrl)
#  verificando formato

# array de 1 dimensão
arrl.shape

[10 21 32 43 48  1  2 64 11 90]


(10,)

Indexaçao

In [22]:
print(arrl[4])

print(arrl[1:4])

indices = [0, 2, 5, 8]
print(arrl[indices])

# criar mask
mask = (arrl % 2 == 0)
print(mask)
print(arrl[mask])

48
[21 32 43]
[10 32  1 11]
[ True False  True False  True False  True  True False  True]
[10 32 48  2 64 90]


Funçoes numpy

In [27]:
#  cumsum - soma acumulada
arrl2 = numpy.array([1, 2, 3, 4, 5])
print(arrl2.cumsum())

#  cumprod - multiplicaçao acumulada - fatorial
print(arrl2.cumprod())

#  arange - cria um array numpy com um progressao aritimetica (start, stop, step)
arr3 = numpy.arange(1, 100, 2)
print(arr3)

[ 1  3  6 10 15]
[  1   2   6  24 120]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
