In [1]:
import numpy as np 


#  Criando uma lista de listas

arr9 = np.array([ [1,2,3], [4,5,6]])


In [4]:
type(arr9)
print(arr9)
print(arr9.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [7]:
lista = [[1,2,3], [4,5,6], [7,8,9]]

# A função matrix cria uma matriz a partir de uma lista de listas

arr11 = np.matrix(lista)

print(arr11)

# tamanho da matriz

print(arr11.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
